server:
  port: 19106

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/how_about_over_there
    username: sunghun
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/ # localhost

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static:
    s3:
      bucket:

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never
