server:
  port: 19094

spring:
  application:
    name: user-service
  data:
    redis:
      host: redis #redis
      port: 6379
      #password: '0000'
      username: default
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/how_about_over_there
    username: sunghun
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/ # eureka-service , localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never