server:
  port: 19096
spring:
  application:
    name: coupon-service
  datasource:
    url: jdbc:postgresql://localhost:5432/how_about_over_there?currentSchema=coupon
    username: sunghun
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 1000
    show-sql: true
  kafka:
    bootstrap-servers: localhost:39092 # localhost:39092 , kafka:9092

  data:
    redis:
      host: localhost # localhost , redis
      port: 6379
      password: '0000'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # localhost , eureka-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never

gateway:
  url: http://gateway-service:19091