server:
  port: 19102
spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/how_about_over_there
    username: sunghun
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
portone:
  api:
    secret: dsfsdf
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never