server:
  port: 19098
spring:
  profiles:
    include: s3
  application:
   name: lodge-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/how_about_over_there
    username: sunghun
    password: 12345
  jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         format_sql: true
     show-sql: true
  data:
    redis:
      host: redis # redis, localhost
      port: 6379
      username: default


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/ #localhost, eureka-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never